name: actions
on:
 push:
  branches:
   - dev
jobs:
 add-check:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
   - name: Run a shell
     run: ./t.sh
   - name: commit
     run: |
       git config --global user.email llleigoing@outlook.com
       git config --global user.name lllei
       git add .
       git commit -m "update"
   - name: push
     uses: ad-m/github-push-action@master
     with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
