name: actions
on:
 push:
  branches:
   - dev
jobs:
 add-check:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
   - name: Run a shell
     run: ./t.sh
   - name: push
     uses: JamesIves/github-pages-deploy-action@v4
     with:
      branch: master
      force: true
